version: '3'
services:
  cavemud:
    hostname: cavemud
    build: .
    ports:
      - "11111:11111"
    networks:
      - cavemud_local_internal
  hitch:
    hostname: hitch
    image: hitch:latest
    ports:
      - "43594:43594"
    volumes:
      - ./hitch.conf:/etc/hitch/hitch.conf
      - ./tls:/etc/hitch/tls
    networks:
      - cavemud_local_internal
    depends_on:
      - cavemud
  database:
    hostname: database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cavemud
      POSTGRES_PASSWORD: cavemud
      POSTGRES_DB: cavemud
    networks:
      - cavemud_local_internal
networks:
  cavemud_local_internal:
    driver: bridge
