//
// Created by Travis Canning on 10/31/22.
//

#ifndef CAVEMUD_TELNETCONSTANTS_H
#define CAVEMUD_TELNETCONSTANTS_H

#include <string>
#include <unordered_map>

enum IAC {
    IAC = 255
};

enum CommandCode {
    SE = 240,
    NOP = 241,
    DATAMARK = 242,
    BREAK = 243,
    INTERRUPT_PROCESS = 244,
    ABORT_OUTPUT = 245,
    ARE_YOU_THERE = 246,
    ERASE_CHARACTER = 247,
    ERASE_LINE = 248,
    GO_AHEAD = 249,
    SB = 250,
    WILL = 251,
    WONT = 252,
    DO = 253,
    DONT = 254
};

// String representations of the command codes
static const std::unordered_map<CommandCode, std::string> command_code_string_map = {
        {SE, "SE"},
        {NOP, "NOP"},
        {DATAMARK, "DATAMARK"},
        {BREAK, "BREAK"},
        {INTERRUPT_PROCESS, "INTERRUPT_PROCESS"},
        {ABORT_OUTPUT, "ABORT_OUTPUT"},
        {ARE_YOU_THERE, "ARE_YOU_THERE"},
        {ERASE_CHARACTER, "ERASE_CHARACTER"},
        {ERASE_LINE, "ERASE_LINE"},
        {GO_AHEAD, "GO_AHEAD"},
        {SB, "SB"},
        {WILL, "WILL"},
        {WONT, "WONT"},
        {DO, "DO"},
        {DONT, "DONT"}
};

enum OptionCode {
    BINARY_TRANSMISSION = 0,
    ECHO = 1,
    RECONNECTION = 2,
    SUPPRESS_GO_AHEAD = 3,
    APPROX_MESSAGE_SIZE_NEGOTIATION = 4,
    STATUS = 5,
    TIMING_MARK = 6,
    REMOTE_CONTROLLED_TRANSMISSION_ECHO = 7,
    OUTPUT_LINE_WIDTH = 8,
    OUTPUT_PAGE_SIZE = 9,
    OUTPUT_CR_DISPOSITION = 10,
    OUTPUT_HORIZONTAL_TAB_STOPS = 11,
    OUTPUT_HORIZONTAL_TAB_DISPOSITION = 12,
    OUTPUT_FORMFEED_DISPOSITION = 13,
    OUTPUT_VERTICAL_TAB_STOPS = 14,
    OUTPUT_VERTICAL_TAB_DISPOSITION = 15,
    OUTPUT_LINEFEED_DISPOSITION = 16,
    EXTENDED_ASCII = 17,
    LOGOUT = 18,
    BYTE_MACRO = 19,
    DATA_ENTRY_TERMINAL = 20,
    SUPDUP = 21,
    SUPDUP_OUTPUT = 22,
    SEND_LOCATION = 23,
    TERMINAL_TYPE = 24,
    END_OF_RECORD = 25,
    TACACS_USER_IDENTIFICATION = 26,
    OUTPUT_MARKING = 27,
    TERMINAL_LOCATION_NUMBER = 28,
    TELNET_3270_REGIME = 29,
    X_3_PAD = 30,
    NEGOTIATE_ABOUT_WINDOW_SIZE = 31,
    TERMINAL_SPEED = 32,
    REMOTE_FLOW_CONTROL = 33,
    LINEMODE = 34,
    X_DISPLAY_LOCATION = 35,
    EXTENDED_OPTIONS_LIST = 255
};

// String representations of the option codes
static const std::unordered_map<OptionCode, std::string> option_code_string_map = {
        {BINARY_TRANSMISSION, "BINARY_TRANSMISSION"},
        {ECHO, "ECHO"},
        {RECONNECTION, "RECONNECTION"},
        {SUPPRESS_GO_AHEAD, "SUPPRESS_GO_AHEAD"},
        {APPROX_MESSAGE_SIZE_NEGOTIATION, "APPROX_MESSAGE_SIZE_NEGOTIATION"},
        {STATUS, "STATUS"},
        {TIMING_MARK, "TIMING_MARK"},
        {REMOTE_CONTROLLED_TRANSMISSION_ECHO, "REMOTE_CONTROLLED_TRANSMISSION_ECHO"},
        {OUTPUT_LINE_WIDTH, "OUTPUT_LINE_WIDTH"},
        {OUTPUT_PAGE_SIZE, "OUTPUT_PAGE_SIZE"},
        {OUTPUT_CR_DISPOSITION, "OUTPUT_CR_DISPOSITION"},
        {OUTPUT_HORIZONTAL_TAB_STOPS, "OUTPUT_HORIZONTAL_TAB_STOPS"},
        {OUTPUT_HORIZONTAL_TAB_DISPOSITION, "OUTPUT_HORIZONTAL_TAB_DISPOSITION"},
        {OUTPUT_FORMFEED_DISPOSITION, "OUTPUT_FORMFEED_DISPOSITION"},
        {OUTPUT_VERTICAL_TAB_STOPS, "OUTPUT_VERTICAL_TAB_STOPS"},
        {OUTPUT_VERTICAL_TAB_DISPOSITION, "OUTPUT_VERTICAL_TAB_DISPOSITION"},
        {OUTPUT_LINEFEED_DISPOSITION, "OUTPUT_LINEFEED_DISPOSITION"},
        {EXTENDED_ASCII, "EXTENDED_ASCII"},
        {LOGOUT, "LOGOUT"},
        {BYTE_MACRO, "BYTE_MACRO"},
        {DATA_ENTRY_TERMINAL, "DATA_ENTRY_TERMINAL"},
        {SUPDUP, "SUPDUP"},
        {SUPDUP_OUTPUT, "SUPDUP_OUTPUT"},
        {SEND_LOCATION, "SEND_LOCATION"},
        {TERMINAL_TYPE, "TERMINAL_TYPE"},
        {END_OF_RECORD, "END_OF_RECORD"},
        {TACACS_USER_IDENTIFICATION, "TACACS_USER_IDENTIFICATION"},
        {OUTPUT_MARKING, "OUTPUT_MARKING"},
        {TERMINAL_LOCATION_NUMBER, "TERMINAL_LOCATION_NUMBER"},
        {TELNET_3270_REGIME, "TELNET_3270_REGIME"},
        {X_3_PAD, "X_3_PAD"},
        {NEGOTIATE_ABOUT_WINDOW_SIZE, "NEGOTIATE_ABOUT_WINDOW_SIZE"},
        {TERMINAL_SPEED, "TERMINAL_SPEED"},
        {REMOTE_FLOW_CONTROL, "REMOTE_FLOW_CONTROL"},
        {LINEMODE, "LINEMODE"},
        {X_DISPLAY_LOCATION, "X_DISPLAY_LOCATION"},
        {EXTENDED_OPTIONS_LIST, "EXTENDED_OPTIONS_LIST"}
};

#endif //CAVEMUD_TELNETCONSTANTS_H
