//
// Created by Travis Canning on 10/31/22.
//

#ifndef CAVEMUD_TELNETCONSTANTS_H
#define CAVEMUD_TELNETCONSTANTS_H

enum IAC {
    IAC = 255
};

enum CommandCode {
    SE = 240,
    NOP = 241,
    DATAMARK = 242,
    BREAK = 243,
    INTERRUPT_PROCESS = 244,
    ABORT_OUTPUT = 245,
    ARE_YOU_THERE = 246,
    ERASE_CHARACTER = 247,
    ERASE_LINE = 248,
    GO_AHEAD = 249,
    SB = 250,
    WILL = 251,
    WONT = 252,
    DO = 253,
    DONT = 254,
};

enum OptionCode {
    BINARY_TRANSMISSION = 0,
    ECHO = 1,
    RECONNECTION = 2,
    SUPPRESS_GO_AHEAD = 3,
    APPROX_MESSAGE_SIZE_NEGOTIATION = 4,
    STATUS = 5,
    TIMING_MARK = 6,
    REMOTE_CONTROLLED_TRANSMISSION_ECHO = 7,
    OUTPUT_LINE_WIDTH = 8,
    OUTPUT_PAGE_SIZE = 9,
    OUTPUT_CR_DISPOSITION = 10,
    OUTPUT_HORIZONTAL_TAB_STOPS = 11,
    OUTPUT_HORIZONTAL_TAB_DISPOSITION = 12,
    OUTPUT_FORMFEED_DISPOSITION = 13,
    OUTPUT_VERTICAL_TAB_STOPS = 14,
    OUTPUT_VERTICAL_TAB_DISPOSITION = 15,
    OUTPUT_LINEFEED_DISPOSITION = 16,
    EXTENDED_ASCII = 17,
    LOGOUT = 18,
    BYTE_MACRO = 19,
    DATA_ENTRY_TERMINAL = 20,
    SUPDUP = 21,
    SUPDUP_OUTPUT = 22,
    SEND_LOCATION = 23,
    TERMINAL_TYPE = 24,
    END_OF_RECORD = 25,
    TACACS_USER_IDENTIFICATION = 26,
    OUTPUT_MARKING = 27,
    TERMINAL_LOCATION_NUMBER = 28,
    TELNET_3270_REGIME = 29,
    X_3_PAD = 30,
    NEGOTIATE_ABOUT_WINDOW_SIZE = 31,
    TERMINAL_SPEED = 32,
    REMOTE_FLOW_CONTROL = 33,
    LINEMODE = 34,
    X_DISPLAY_LOCATION = 35,
    EXTENDED_OPTIONS_LIST = 255
};

#endif //CAVEMUD_TELNETCONSTANTS_H
