//
// Created by Travis Canning on 11/19/22.
//

#ifndef CAVEMUD_KV_KEYS_H
#define CAVEMUD_KV_KEYS_H

#define SESSION_KV_AYT_FLAG "FLAG_AYT"
#define SESSION_KV_INTERRUPT_FLAG "FLAG_INTERRUPT"
#define SESSION_KV_DESTROY_FLAG "FLAG_DESTROY"

#endif //CAVEMUD_KV_KEYS_H
