//
// Created by Travis Canning on 11/19/22.
//

#ifndef CAVEMUD_KV_KEYS_H
#define CAVEMUD_KV_KEYS_H

#define SESSION_KV_AYT_FLAG "FLAG_AYT"
#define SESSION_KV_INTERRUPT_FLAG "FLAG_INTERRUPT"
#define SESSION_KV_DESTROY_FLAG "FLAG_DESTROY"

#define SESSION_KV_COMMAND_PREPEND_BUFFER "COMMAND_PREPEND_BUFFER"
#define SESSION_KV_COMMAND_APPEND_BUFFER "COMMAND_APPEND_BUFFER"

#endif //CAVEMUD_KV_KEYS_H
