name: build-cavemud-server
run-name: ${{ github.actor }} is building ${{ github.repository }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git curl zip unzip tar ninja-build pkg-config make autoconf autoconf-archive g++ gcc
      - name: Install VCPKG
        run: |
          export VCPKG_FORCE_SYSTEM_BINARIES=1 && \
              git clone https://github.com/microsoft/vcpkg.git && \
              ./vcpkg/bootstrap-vcpkg.sh && \
              ./vcpkg/vcpkg install --feature-flags=manifests
      - name: Run cmake build
        run: |
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build
      - name: Run unit tests
        run: |
          cd ${{ github.workspace }}/build/Tests
          chmod +x CaveMUD_tests
          ./CaveMUD_tests
